# .github/workflows/build.yml
name: Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@v3.2.4

    - name: Install dependencies
      run: |
        uv python install 3.11
        uv venv
        uv sync

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        uv run flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Lint with black
      run: |
        uv run black --target-version py311 --check src tests

    - name: Build package
      run: |
        uv build
